### ISSUE TITLE
在调用时oneforall会一直报错

### ISSUE THREAD

**Issue by DatangST** [komomon/Komo#11]
![image](https://user-images.githubusercontent.com/52750566/230111792-03dfd684-9a3e-42f1-827a-b4dd6d621076.png)

**Comment by komomon** [comment]
> ![image](https://user-images.githubusercontent.com/52750566/230111792-03dfd684-9a3e-42f1-827a-b4dd6d621076.png)

你是不是改过代码，oneforall的路径错了，OneForAll/oneforall.py，图上的是oneforall
![image](https://user-images.githubusercontent.com/52700174/230259971-26a19a07-868f-4f78-aa3b-2dbc2e299bd3.png)

**Comment by komomon** [comment]
可以下载最新代码，再试试，如果有bug可以及时与我反馈
