### ISSUE TITLE
install后会有一个tmp目录里面的tool要解压嘛

### ISSUE THREAD

**Issue by DatangST** [komomon/Komo#12]
![image](https://user-images.githubusercontent.com/52750566/231038136-1157ac61-496f-480b-9fe9-725300a32e9c.png)

**Comment by komomon** [comment]
komo会自动解压，这个目录不用管，如果install后，运行正常，也可以删掉。

**Comment by DatangST** [comment]
我在批量跑的时候，在result/ 有无批量跑的域名总和在一起的。看着好乱。而且oneforall一直跑的是空很奇怪。
![image](https://user-images.githubusercontent.com/52750566/231041980-27be250b-2c41-41e3-9082-35c027bbd002.png)
QQ群，哪位是师傅一直找不到

**Comment by komomon** [comment]
目前没设计把多个域名的oneforall结果合到一起，分类是为了方便分类看，因为一起跑的多个域名可能涉及到不同的项目。这个得结合日志和你跑的域名看了。群管理，昵称：那xxx

**Comment by komomon** [comment]
> 我在批量跑的时候，在result/ 有无批量跑的域名总和在一起的。看着好乱。而且oneforall一直跑的是空很奇怪。 ![image](https://user-images.githubusercontent.com/52750566/231041980-27be250b-2c41-41e3-9082-35c027bbd002.png) QQ群，哪位是师傅一直找不到

你是下载的beta分支的代码吗，beta分支已更新，你可以copy core\tools\domain\domain_main.py的代码覆盖一下就可以解决这个问题了。
