### ISSUE TITLE
执行所有命令都报No such file or directory

### ISSUE THREAD

**Issue by Yohansun** [komomon/Komo#15]
File "/var/ios/Komo-main/core/tools/sensitiveinfo/sensitiveinfo_main.py", line 904, in run
    with open(urlsfile, "r", encoding="utf-8") as f:
              └ 'result/2023-05-18-19-31-52/baidu.com.subdomains.with.http.txt'

FileNotFoundError: [Errno 2] No such file or directory: 'result/2023-05-18-19-31-52/baidu.com.subdomains.with.http.txt'

**Comment by komomon** [comment]
是否用install下载了所有工具呢，推荐下载beta分支，也不建议直接带攻击全扫baidu，你懂得
