### ISSUE TITLE
finger扫描有问题

### ISSUE THREAD

**Issue by d4ydramer** [komomon/Komo#17]
![image](https://github.com/komomon/Komo/assets/65070121/a752f762-02e2-4504-8b8c-1b4136ad5633)

感觉代码逻辑好像有点问题，file来自urlfile，file = None了，为什么还用urlfile来创建文件

![image](https://github.com/komomon/Komo/assets/65070121/d35c093e-922c-480e-ab5a-35bcd01172bd)

**Comment by komomon** [comment]
如果你提供的单个url，komo会生成一个临时文件存储这个url，就像你传递的是一个urlfile一样，然后去扫描，为了调用的连续性
