### ISSUE TITLE
amass输出json

### ISSUE THREAD

**Issue by jacknhk** [komomon/Komo#19]
我在使用的时候报错了：
F:\mybox\ScanTools\Komo-beta\Komo-beta\core\tools\domain\amass> amass.exe enum -active -brute -max-depth 3 -d api.doppler.com -json result/2023-09-06-12-35-49/domain_log/api.doppler.com.amass.json
flag provided but not defined: -json

根据amass官方的说法，amass在使用db命令的好像才能输出json格式的文本，amass db -names -silent -json out.json -d example.com ；在使用enum的时候只有 amass enum -o out.txt -d example.com  输出txt格式；

**Comment by komomon** [comment]
你用的amass什么版本呢

**Comment by jacknhk** [comment]
> 你用的amass什么版本呢

最新版本。。

**Comment by komomon** [comment]
> > 你用的amass什么版本呢
> 
> 最新版本。。

使用install komo会自动下载指定版本的amass，其他版本未做适配，不能保证不出问题。
