### ISSUE TITLE
如何下载chromuim-linux

### ISSUE THREAD

**Issue by gtasb** [komomon/Komo#22]
我安装了Komo在KALI上，但不知道去哪里下载这个呢
![image](https://github.com/komomon/Komo/assets/123642409/6aadfa22-9c7e-4ad1-a171-00b5a33b3a02)

**Comment by komomon** [comment]
https://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/1086242/chrome-linux.zip,国内下载不了，需要翻墙

**Comment by komomon** [comment]
komo也有挂代理下载的参数
