### ISSUE TITLE
我就扫个靶场，结果爬了一堆乱七八糟的链接

### ISSUE THREAD

**Issue by Sq-CC** [komomon/Komo#4]
![image](https://user-images.githubusercontent.com/58176451/217159063-9569966d-75d0-4775-8285-5800e38e142b.png)
![image](https://user-images.githubusercontent.com/58176451/217159132-6a0dd87d-aa9e-4fd6-90b0-0b865c1bebfa.png)

**Comment by komomon** [comment]
这个网站的包括调用其他域名的资源所以链接也会爬取下来，但是除了crawlergo rad外其他爬取工具会先进行校验是不是该域名的，是的话才会传给xray，图二应该是crawlergo或rad爬取的，这两个工具为了效率是直接把请求原封不动的传递给xray的，其他爬取工具都会校验

**Comment by komomon** [comment]
> 这个网站的包括调用其他域名的资源所以链接也会爬取下来，但是除了crawlergo rad外其他爬取工具会先进行校验是不是该域名的，是的话才会传给xray，图二应该是crawlergo或rad爬取的，这两个工具为了效率是直接把请求原封不动的传递给xray的，其他爬取工具都会校验

宁可多扫描，也不漏掉一个，这样做是在效率速度和扫描质量之间做的权衡
