### ISSUE TITLE
只进行资产扫描需要多久，为何会在子域名收集时卡住不动

### ISSUE THREAD

**Issue by HiIkll** [komomon/Komo#5]

**Comment by komomon** [comment]
会扫描三级子域名，所以会比较慢，没有卡住，资产大就会有点慢的感觉

**Comment by ViCrack** [comment]
理论上多的时候起码卡半小时。。。。

**Comment by komomon** [comment]
> 理论上多的时候起码卡半小时。。。。

默认会扫描三级域名，主要是amass慢，让他识别了三级子域，扫三级子域所需的时间是二级子域扫描时间的数倍，等同于提供了相当于二级域名数量的主域名，所以就会很慢，如果介意可以去[core](https://github.com/komomon/Komo/tree/beta/core)/[tools](https://github.com/komomon/Komo/tree/beta/core/tools)/[domain](https://github.com/komomon/Komo/tree/beta/core/tools/domain)/domain_main.py 591行注释掉amass()
