### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by ViCrack** [komomon/Komo#6]
师傅我刚刚试用了一下，发现可能有些地方可以优化的

1、我改成用proxy地址加速下载了，速度飞起
![图片](https://user-images.githubusercontent.com/18179821/223399358-f93d92cb-27d0-4e00-a5a5-5cbe6321715c.png)

2、泛解析代码改成用dns.resolver.resolve
![图片](https://user-images.githubusercontent.com/18179821/223399540-e5920d8b-b93e-40d4-ab3f-c3548a6f34ad.png)

高版本库会报错（有待考证）
2023-03-07 15:20:18.719 | INFO     | core.tools.domain.domain_main:checkPanAnalysis:38 - [Not PanAnalysis] :("module 'dns' has no attribute 'resolver'",)

3、可以考虑增加一个超时设置，和进度条参数
![图片](https://user-images.githubusercontent.com/18179821/223400303-14ee7ec8-2759-4166-820f-c0ab9928753b.png)
我发现这工具默认会枚举很久，就像是卡住了一样
![图片](https://user-images.githubusercontent.com/18179821/223400514-188af627-291c-4acc-b33d-165831c7bb91.png)

4、xray等工具我配成了动态ip了
这样可以用上分布式，不一定是127.0.0.1
![图片](https://user-images.githubusercontent.com/18179821/223400847-a17b5d2b-c7ae-4d26-a3f8-4267af79a4f4.png)

**Comment by komomon** [comment]
感谢，部分内容我会进行采纳整合。amass确实慢，让他识别了三级子域，扫三级子域所需的时间是二级子域扫描时间的数倍，等同于提供了相当于二级域名数量的主域名，所以就会很慢。ヽ(*^ｰ^)人(^ｰ^*)ノ

**Comment by peterzyk** [comment]
可以适配m1嘛，哭死

**Comment by komomon** [comment]
> 可以适配m1嘛，哭死

目前，还没计划，可以考虑虚拟机运行
