### ISSUE TITLE
Linux遇到的问题

### ISSUE THREAD

**Issue by zaneSSS** [komomon/Komo#7]
不知是否广泛存在，还是个人环境问题，待求证，
1、URLFinder工具无法执行，可能是下载链接存在问题，解决方案：手动下载导入。
2、OneForAll 调用大小写问题，路径问题，需要修改源码
<img width="882" alt="image" src="https://user-images.githubusercontent.com/44695853/223936808-add6d761-0023-4d2a-87da-fee15b0dbae9.png">

**Comment by komomon** [comment]
建议使用beta分支，为最新代码，main分支，这段时间不更新，后面会更新，URLFinder项目下载的url地址变了，所以导致下载失败。
